### ISSUE TITLE
[求助] 机器人对部分命令无反应。

### ISSUE THREAD

**Issue by XXY233** [Fader282/Koinoribot-plugins-for-Hoshino#2]
我部署机器人后发现，`冰祈帮助` 和 `#钓鱼帮助` 两个命令都没反应（不知道还有没有命令也是这样，其他没测试过），但是 `签到` 有反应。如图：

![QQ图片20230414114853](https://user-images.githubusercontent.com/46647646/231936920-d396efdd-40cb-4fd8-bf44-e1bb7e61d1c6.png)

**Comment by Fader282** [comment]
`冰祈帮助`指令为hoshino自带功能，可以在`hoshino/modules/botmanage/help.py`中自定义；
指令无反应的原因有很多，如：插件未加载、插件运行中出错导致没有响应等，具体的原因排查需要提供一下控制台的截图。

**Comment by XXY233** [comment]
不知道 `#钓鱼帮助` 、 `#钓鱼` 指令为什么无反应，希望这些信息可以提供帮助：

CQ-HTTP 控制台：https://paste.gg/p/XXY233/cbe4c1ff3d9c4682a1bf4ecb7143eebe
Hoshino 控制台：https://paste.gg/p/XXY233/e8828fd7fb1c4427b787a9e58a2d920d
